# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Build pipeline
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.calculate-version.outputs.version-string }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup Go
        uses: actions/setup-go@v4
        with: 
          go-version: '1.22'
      - name: Configure version information
        id: calculate-version
        if: ${{ github.event_name == 'push' }}
        uses: bitshifted/git-auto-semver@v1
        with:
          create_tag: true
          initial_version: 0.1.0
      - name: Setup environment variables
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "VERSION=${{ steps.calculate-version.outputs.version-string }}" >> $GITHUB_ENV
          echo "GIT_COMMIT_ID=$(echo $GITHUB_SHA)" >> $GITHUB_ENV
      - name: Build
        if: ${{ github.event_name != 'push' }}
        run: |
          make build
      - name: Package
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "VERSION: $VERSION"
          echo "GIT_COMMIT_ID: $GIT_COMMIT_ID"
          make package
      - name: Upload Linux binary
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v4
        with:
          name: liftoff-binary-linux
          path: target/linux-amd64/liftoff
      - name: Upload release artifacts
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v4
        with:
          name: dist-packages
          path: target/dist
  # Docker image publishing
  publish-docker-image:
    if:  ${{ github.event_name == 'push' }}
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: liftoff-binary-linux
          path: target/linux-amd64/liftoff
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build timestamp
        id: docker-build-timestamp
        run: |
          TIMESTAMP=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo "ts_value=$TIMESTAMP" >> $GITHUB_OUTPUT
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          build-args: |
            BUILD_DATE=${{ steps.docker-build-timestamp.outputs.ts_value }}
            BUILD_VERSION=${{ needs.build-and-test.outputs.version }}
            VCS_REF=${{ github.sha }}
          tags: ghcr.io/bitshifted/liftoff:${{ needs.build-and-test.outputs.version }}
  # Create release
  create-release:
    if:  ${{ github.event_name == 'push' }}
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Download binary artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-packages
          path: target/dist
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelase: false
          generate_release_notes: true
          tag_name: v${{ needs.build-and-test.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            target/dist/liftoff-linux-amd64-${{ needs.build-and-test.outputs.version }}.tar.gz
            target/dist/liftoff-linux-arm64-${{ needs.build-and-test.outputs.version }}.tar.gz
            target/dist/liftoff-mac-amd64-${{ needs.build-and-test.outputs.version }}.tar.gz
            target/dist/liftoff-mac-arm64-${{ needs.build-and-test.outputs.version }}.tar.gz
            target/dist/liftoff-windows-amd64-${{ needs.build-and-test.outputs.version }}.zip
            target/dist/liftoff-windows-arm64-${{ needs.build-and-test.outputs.version }}.zip
